version: "3.8"

services:
  control-gastos:
    build: .
    container_name: control-gastos-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/backend/data
      - ./uploads:/app/backend/uploads
    environment:
      - NODE_ENV=production
      - PORT=3000
