services:
  control-gastos:
    build: .
    container_name: control-gastos-app
    restart: unless-stopped
    networks:
      - dokploy-network
    volumes:
      - ./data:/app/backend/data
      - ./uploads:/app/backend/uploads
    environment:
      - NODE_ENV=production
      - PORT=3000

networks:
  dokploy-network:
    external: true
